services:
  app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-app-backend
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER:-hrapp}:${DB_PASSWORD:-hrapp123}@${DB_HOST:-host.docker.internal}:5432/${DB_NAME:-hr_app_db}?schema=public
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://${RABBITMQ_USER:-hrapp}:${RABBITMQ_PASSWORD:-hrapp123}@${RABBITMQ_HOST:-host.docker.internal}:5672}
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - hr-app-network
    command: sh -c "pnpm exec prisma generate && pnpm prisma migrate deploy && pnpm run migrate:tenants && node dist/src/main"

networks:
  hr-app-network:
    driver: bridge
