services:
  postgres:
    image: postgres:16-alpine
    container_name: hr-app-postgres
    restart: always
    environment:
      POSTGRES_USER: hrapp
      POSTGRES_PASSWORD: hrapp123
      POSTGRES_DB: hr_app_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hrapp']
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    ports:
      - "9093:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: >
        PLAINTEXT://broker:29092,
        PLAINTEXT_HOST://0.0.0.0:9092,
        CONTROLLER://broker:29093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://broker:29092,
        PLAINTEXT_HOST://localhost:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --list"
        ]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data:
